### ISSUE TITLE
Standard PTDF Formulation Duplicates Line Rate Constraints

### ISSUE THREAD

**Issue by jmaack24** [NREL/PowerSimulations.jl#394] opened 2020-03-24 15:22 UTC
Seems to be the result of calling `device_range` twice in the function `branch_rate_constraints!` which is declared in lines 116 to 151 of AC_branches.jl on the master branch.

**Comment by jd-lara** [comment] 2020-03-24 22:27
This is a duplicate of #384

**Closed** 2020-03-27 16:08 UTC
Labels: duplicate
