### ISSUE TITLE
PSI.construct_device! in test fails with `ERROR: UndefRefError: access to undefined reference`

### ISSUE THREAD

**Issue by ianfiske** [NREL/PowerSimulations.jl#138] opened 2019-05-02 17:57 UTC
Exerpted from runtests.jl and thermal_generation_constructors.jl, 

```
using PowerSimulations
using PowerSystems
using PowerModels
using JuMP
using Test
using Ipopt
using GLPK
using OSQP

# required for reducing logging during tests
using Memento

const PM = PowerModels
const PSY = PowerSystems
const PSI = PowerSimulations

abstract type TestOptModel <: PSI.AbstractOperationsModel end

ipopt_optimizer = with_optimizer(Ipopt.Optimizer, print_level = 0)
GLPK_optimizer = with_optimizer(GLPK.Optimizer)
OSQP_optimizer = with_optimizer(OSQP.Optimizer)

time_range = 1:24

base_dir = string(dirname(dirname(pathof(PowerSystems))));
include(joinpath(base_dir,"data/data_5bus_pu.jl"));
bus_numbers = [b.number for b in nodes5]

include(joinpath(base_dir,"data/data_14bus_pu.jl"))
sys14 = PSY.System(nodes14, generators14, loads14, branches14, nothing,  100.0);

DATA_DIR = joinpath(base_dir, "data")
RTS_GMLC_DIR = joinpath(DATA_DIR, "RTS_GMLC")
cdm_dict = PSY.csv2ps_dict(RTS_GMLC_DIR, 100.0)

for v in values(cdm_dict["load"])
    v["scalingfactor"] = v["scalingfactor"][1:24]
end

for source in values(cdm_dict["gen"]["Renewable"]["PV"])
    source["scalingfactor"] = source["scalingfactor"][1:24]
end

for source in values(cdm_dict["gen"]["Renewable"]["RTPV"])
    source["scalingfactor"] = source["scalingfactor"][1:24]
end

for source in values(cdm_dict["gen"]["Renewable"]["WIND"])
    source["scalingfactor"] = source["scalingfactor"][1:24]
end

for source in values(cdm_dict["gen"]["Hydro"])
    source["scalingfactor"] = source["scalingfactor"][1:24]
end

sys_rts = PSY.System(cdm_dict);

generators5_uc = [  ThermalDispatch("Alta", true, nodes5[1],
                    TechThermal(0.40, (min=0.0, max=0.40), 0.010, (min = -0.30, max = 0.30), nothing, nothing),
                    EconThermal(0.40, x -> x*14.0, 0.0, 4.0, 2.0, nothing)
                    #EconThermal(40.0, x -> x*14.0, 4.0, 4.0, 2.0, nothing)

                ),
                ThermalDispatch("Park City", true, nodes5[1],
                    TechThermal(1.70, (min=0.0, max=1.70), 0.20, (min =-1.275, max=1.275), (up=0.50, down=0.50), (up=2.0, down=1.0)),
                    EconThermal(1.70, x -> x*15.0, 0.0, 1.5, 0.75, nothing)
                    #EconThermal(170.0, x -> x*15.0, 1.5, 1.5, 0.75, nothing)

                ),
                ThermalDispatch("Solitude", true, nodes5[3],
                    TechThermal(5.20, (min=0.0, max=5.20), 1.00, (min =-3.90, max=3.90), (up=0.520, down=0.520), (up=3.0, down=2.0)),
                    EconThermal(5.20, x -> x*30.0, 0.0, 3.0, 1.5, nothing)
                    #EconThermal(520.0, x -> x*30.0, 3.0, 3.0, 1.5, nothing)

                ),
                ThermalDispatch("Sundance", true, nodes5[4],
                    TechThermal(2.0, (min=0.0, max=2.0), 0.40, (min =-1.5, max=1.5), (up=0.50, down=0.50), (up=2.0, down=1.0)),
                    EconThermal(2.0, x -> x*40.0, 0.0, 4.0, 2.0, nothing)
                    #EconThermal(200.0, x -> x*40.0, 4.0, 4.0, 2.0, nothing)

                ),
                ThermalDispatch("Brighton", true, nodes5[5],
                    TechThermal(6.0, (min=0.0, max=6.0), 1.50, (min =-4.50, max=4.50), (up=0.50, down=0.50), (up=5.0, down=3.0)),
                    #EconThermal(600.0, [(0.0, 0.0), (450.0, 8.0), (600.0, 10.0)], 0.0, 0.0, 0.0, nothing)
                    EconThermal(6.0, x -> x*10.0, 0.0, 0.0, 0.0, nothing))];



sys5b_uc = PSY.System(nodes5, generators5_uc, loads5_DA, branches5, nothing,  100.0);

ps_model = PSI._canonical_model_init(bus_numbers, nothing, PM.AbstractPowerFormulation, time_range; parameters = false)
PSI.construct_device!(ps_model, PSY.ThermalGen, PSI.ThermalUnitCommitment, PM.DCPlosslessForm, sys5b_uc, time_range; parameters = false);
```
gives
```
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:730 [inlined]
 [2] getindex at /Users/ifiske/.julia/packages/JuMP/jnmGG/src/Containers/DenseAxisArray.jl:161 [inlined]
 [3] _add_to_expression!(::JuMP.Containers.DenseAxisArray{GenericAffExpr{Float64,VariableRef},2,Tuple{Array{Int64,1},UnitRange{Int64}},Tuple{Dict{Int64,Int64},Dict{Int64,Int64}}}, ::Int64, ::Int64, ::VariableRef) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_models/common/expressionarray_algebra.jl:51
 [4] add_variable(::PowerSimulations.CanonicalModel, ::Array{ThermalDispatch,1}, ::UnitRange{Int64}, ::Symbol, ::Bool, ::Symbol) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_models/common/add_variable.jl:32
 [5] activepower_variables(::PowerSimulations.CanonicalModel, ::Array{ThermalDispatch,1}, ::UnitRange{Int64}) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_models/thermal_generation.jl:24
 [6] #construct_device!#108(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:parameters,),Tuple{Bool}}}, ::Function, ::PowerSimulations.CanonicalModel, ::Type{ThermalGen}, ::Type{PowerSimulations.ThermalUnitCommitment}, ::Type{DCPlosslessForm}, ::System, ::UnitRange{Int64}) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_constructors/thermalgeneration_constructor.jl:66
 [7] (::getfield(PowerSimulations, Symbol("#kw##construct_device!")))(::NamedTuple{(:parameters,),Tuple{Bool}}, ::typeof(PowerSimulations.construct_device!), ::PowerSimulations.CanonicalModel, ::Type{ThermalGen}, ::Type{PowerSimulations.ThermalUnitCommitment}, ::Type{DCPlosslessForm}, ::System, ::UnitRange{Int64}) at ./none:0
 [8] top-level scope at none:0
```

my packages are
```
pkg> st
    Status `~/irdot/SimulatorPrototype/Project.toml`
  [31a5f54b] Debugger v0.4.0
  [60bf3e95] GLPK v0.9.1
  [2030c09a] InfrastructureModels v0.3.0 #moi-2 (https://github.com/lanl-ansi/InfrastructureModels.jl.git)
  [4076af6c] JuMP v0.19.0
  [ab2f91bb] OSQP v0.5.1
  [774612a8] ParameterJuMP v0.1.0
  [d96e819e] Parameters v0.10.3
  [c36e90e8] PowerModels v0.10.0 #moi-2 (https://github.com/lanl-ansi/PowerModels.jl.git)
  [e690365d] PowerSimulations v0.1.0 [`~/.julia/dev/PowerSimulations`]
  [bcd98974] PowerSystems v0.3.1
  [9e3dc215] TimeSeries v0.14.1
```

I'm trying to run through the tests to gain some intuition about how to use `PowerSimulations`.  I've already locally fixed the `Parameter`->`ParameterRef` types to get this far.  Maybe there are some unlisted version compatibility requirements?

I stepped into the `getindex` function from JuMP, but didn't see anything obviously problematic there.  So the bug might be in JuMP's DenseAxisArray?

**Comment by jd-lara** [comment] 2019-05-02 18:16
This error is produced by trying to get a value from an Array that has `#undef` values inside which seems like a bug in expression algebra.

**Comment by ianfiske** [comment] 2019-05-02 18:28
Ah, thanks that makes sense because
```
debug> A
5×24 Array{GenericAffExpr{Float64,VariableRef},2}:
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef
```

This cause surprised me because for some types (maybe bitstypes?), this is a bit different:
```
julia> Array{Float64}(undef, 5)[1]
2.4506792543e-314

julia> Array{Int64}(undef, 5)[1]
4990445296

julia> Array{NamedTuple}(undef, 5)[1]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex(::Array{NamedTuple,1}, ::Int64) at /Applications/Julia-1.1.app/Contents/Resources/julia/share/julia/base/array.jl:729
 [2] top-level scope at none:0
```

**Comment by jd-lara** [comment] 2019-05-02 18:38
It surprises me that is failing there since there weren't significant changes in the dependent packages and the tests show as passing.

**Comment by ianfiske** [comment] 2019-05-02 18:46
Agreed -- I noticed the same.  Is it failing for you locally too, or just for me?

**Comment by jd-lara** [comment] 2019-05-02 18:48
I have a different branch for development right now. I will try to fix this in master and deploy a patch.

**Comment by jd-lara** [comment] 2019-05-02 19:09
I don't seem to be able to reproduce the error. I just ran the whole test set and the script provided and can't make it generate the error. Can you paste the package versions in your environment, please.

**Comment by ianfiske** [comment] 2019-05-02 19:16
Sure thing.

```
pkg> st -m
    Status `~/irdot/SimulatorPrototype/Manifest.toml`
  [39de3d68] AxisArrays v0.3.0
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.4
  [336ed68f] CSV v0.4.3
  [49dc2e85] Calculus v0.4.1
  [324d7699] CategoricalArrays v0.5.2
  [da1fd8a2] CodeTracking v0.5.7
  [19ecbf4d] Codecs v0.5.0
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.1.0
  [a8cc5b0e] Crayons v4.0.0
  [a93c6f00] DataFrames v0.18.1
  [9a8bc11e] DataStreams v0.4.1
  [864edb3b] DataStructures v0.15.0
  [31a5f54b] Debugger v0.4.0
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [ffbed154] DocStringExtensions v0.7.0
  [8f5d6c58] EzXML v0.9.1
  [f6369f11] ForwardDiff v0.10.3
  [60bf3e95] GLPK v0.9.1
  [eafb193a] Highlights v0.3.1
  [2030c09a] InfrastructureModels v0.3.0 #moi-2 (https://github.com/lanl-ansi/InfrastructureModels.jl.git)
  [8197267c] IntervalSets v0.3.1
  [c8e1da08] IterTools v1.1.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [682c06a0] JSON v0.20.0
  [4076af6c] JuMP v0.19.0
  [aa1ae85d] JuliaInterpreter v0.5.0
  [f8899e07] LinQuadOptInterface v0.6.0
  [b8f27783] MathOptInterface v0.8.4
  [fdba3010] MathProgBase v0.7.7
  [f28f55f0] Memento v0.12.1
  [e1d29d7a] Missings v0.4.0
  [78c3b35d] Mocking v0.5.7
  [77ba4419] NaNMath v0.3.2
  [4d1e1d77] Nullables v0.0.8
  [ab2f91bb] OSQP v0.5.1
  [bac558e1] OrderedCollections v1.1.0
  [774612a8] ParameterJuMP v0.1.0
  [d96e819e] Parameters v0.10.3
  [69de0a69] Parsers v0.2.22
  [2dfb63ee] PooledArrays v0.5.1
  [c36e90e8] PowerModels v0.10.0 #moi-2 (https://github.com/lanl-ansi/PowerModels.jl.git)
  [e690365d] PowerSimulations v0.1.0 [`~/.julia/dev/PowerSimulations`]
  [bcd98974] PowerSystems v0.3.1
  [b3c3ace0] RangeArrays v0.3.1
  [3cdcf5f2] RecipesBase v0.6.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [a2af1166] SortingAlgorithms v0.3.1
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.10.3
  [2913bbd2] StatsBase v0.30.0
  [cea106d9] Syslogs v0.2.0
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v0.2.0
  [9e3dc215] TimeSeries v0.14.1
  [f269a46b] TimeZones v0.9.0
  [30578b45] URIParser v0.4.0
  [ea10d353] WeakRefStrings v0.5.8
  [ddb6d928] YAML v0.3.2
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [9fa8497b] Future 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [9abbd945] Profile 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode
```

**Comment by jd-lara** [comment] 2019-05-02 19:19
I see, the difference is the ParameterJuMP version. I think that's the breaking update.

**Comment by jd-lara** [comment] 2019-05-02 19:47
@ianfiske the problem here is the version of ParameterJuMP. I just submitted a PR that is waiting for the tests to pass that will pin the version to the correct one. As soon as that one is merged you can update master and run a resolve to get the proper version.

**Closed** 2019-05-02 20:18 UTC
Labels: Upstream

**Comment by ianfiske** [comment] 2019-05-02 20:33
Awesome, thanks for the quick fix @jd-lara !

**Comment by jd-lara** [comment] 2019-05-02 20:38
np, hopefully we will be depending on a more stable version of ParameterJuMP soon.

**Comment by ianfiske** [comment] 2019-05-02 20:55
Hmmm, so I'm not sure this fixes for me.  I have the newly recommended version of ParameterJuMP:
```
pkg> st
    Status `~/irdot/SimulatorPrototype/Project.toml`
  [31a5f54b] Debugger v0.4.0
  [60bf3e95] GLPK v0.9.1
  [2030c09a] InfrastructureModels v0.3.0 #moi-2 (https://github.com/lanl-ansi/InfrastructureModels.jl.git)
  [4076af6c] JuMP v0.19.0
  [ab2f91bb] OSQP v0.5.1
  [774612a8] ParameterJuMP v0.0.1 #dfb1e3c (https://github.com/JuliaStochOpt/ParameterJuMP.jl.git)
  [d96e819e] Parameters v0.10.3
  [c36e90e8] PowerModels v0.10.0 #moi-2 (https://github.com/lanl-ansi/PowerModels.jl.git)
  [e690365d] PowerSimulations v0.1.0 [`~/.julia/dev/PowerSimulations`]
  [bcd98974] PowerSystems v0.3.1
  [9e3dc215] TimeSeries v0.14.1
```

But still, the same error in the tests.  Of course I reverted my Parameter -> ParameterRef changes to make things run again.

```
julia> sys5b_uc = PSY.System(nodes5, generators5_uc, loads5_DA, branches5, nothing,  100.0);
[ Info: Ramp defined as nothing for Alta
┌ Warning: The generator Park City has a nonbinding ramp up limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:118
┌ Warning: The generator Park City has a nonbinding ramp down limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:121
┌ Warning: The generator Solitude has a nonbinding ramp up limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:118
┌ Warning: The generator Solitude has a nonbinding ramp down limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:121
┌ Warning: The generator Sundance has a nonbinding ramp up limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:118
┌ Warning: The generator Sundance has a nonbinding ramp down limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:121
┌ Warning: The generator Brighton has a nonbinding ramp up limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:118
┌ Warning: The generator Brighton has a nonbinding ramp down limit.
└ @ PowerSystems ~/.julia/packages/PowerSystems/mrBWF/src/utils/IO/system_checks.jl:121

julia> ps_model = PSI._canonical_model_init(bus_numbers, nothing, PM.AbstractPowerFormulation, time_range; parameters = false)
[ Info: The optimization model has no optimizer attached
PowerSimulations.CanonicalModel(A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached., Dict{Symbol,JuMP.Containers.DenseAxisArray}(), Dict{Symbol,JuMP.Containers.DenseAxisArray}(), 0, Dict{Symbol,JuMP.Containers.DenseAxisArray}(:var_reactive=>2-dimensional DenseAxisArray{GenericAffExpr{Float64,VariableRef},2,...} with index sets:
    Dimension 1, [1, 2, 3, 4, 5]
    Dimension 2, 1:24
And data, a 5×24 Array{GenericAffExpr{Float64,VariableRef},2}:
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef,:var_active=>2-dimensional DenseAxisArray{GenericAffExpr{Float64,VariableRef},2,...} with index sets:
    Dimension 1, [1, 2, 3, 4, 5]
    Dimension 2, 1:24
And data, a 5×24 Array{GenericAffExpr{Float64,VariableRef},2}:
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef), nothing, Dict{Symbol,Array{PowerSimulations.InitialCondition,N} where N}(), nothing)

julia> PSI.construct_device!(ps_model, PSY.ThermalGen, PSI.ThermalUnitCommitment, PM.DCPlosslessForm, sys5b_uc, time_range; parameters = false);
┌ Warning: Initial Conditions not provided, this can lead to infeasible problem formulations
└ @ PowerSimulations ~/.julia/dev/PowerSimulations/src/devices/device_constructors/thermalgeneration_constructor.jl:62
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:730 [inlined]
 [2] getindex at /Users/ifiske/.julia/packages/JuMP/jnmGG/src/Containers/DenseAxisArray.jl:161 [inlined]
 [3] _add_to_expression!(::JuMP.Containers.DenseAxisArray{GenericAffExpr{Float64,VariableRef},2,Tuple{Array{Int64,1},UnitRange{Int64}},Tuple{Dict{Int64,Int64},Dict{Int64,Int64}}}, ::Int64, ::Int64, ::VariableRef) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_models/common/expressionarray_algebra.jl:51
 [4] add_variable(::PowerSimulations.CanonicalModel, ::Array{ThermalDispatch,1}, ::UnitRange{Int64}, ::Symbol, ::Bool, ::Symbol) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_models/common/add_variable.jl:32
 [5] activepower_variables(::PowerSimulations.CanonicalModel, ::Array{ThermalDispatch,1}, ::UnitRange{Int64}) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_models/thermal_generation.jl:24
 [6] #construct_device!#108(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:parameters,),Tuple{Bool}}}, ::Function, ::PowerSimulations.CanonicalModel, ::Type{ThermalGen}, ::Type{PowerSimulations.ThermalUnitCommitment}, ::Type{DCPlosslessForm}, ::System, ::UnitRange{Int64}) at /Users/ifiske/.julia/dev/PowerSimulations/src/devices/device_constructors/thermalgeneration_constructor.jl:66
 [7] (::getfield(PowerSimulations, Symbol("#kw##construct_device!")))(::NamedTuple{(:parameters,),Tuple{Bool}}, ::typeof(PowerSimulations.construct_device!), ::PowerSimulations.CanonicalModel, ::Type{ThermalGen}, ::Type{PowerSimulations.ThermalUnitCommitment}, ::Type{DCPlosslessForm}, ::System, ::UnitRange{Int64}) at ./none:0
 [8] top-level scope at none:0
```

**Comment by jd-lara** [comment] 2019-05-02 21:03
@ianfiske there are also breaking changes in JuMP. Will push a fix and update the instruction. Thanks for the feedback.
